name: Weather Application

on: [push]

jobs:
  
  build:

    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        cd server/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build Client and Test
      run: |
        cd client/ 
        npm install
        npm run build --if-present
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy

    steps:
    - uses: appleboy/ssh-action@master
    - name: Deploy
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.KEY_SECRET }}
        port: ${{ secrets.PORT }}
        scripts: |
          cd /var/www/ 
          git pull origin master
          git status
